ALTER TABLE doctors ADD COLUMN IF NOT EXISTS clinic_address VARCHAR(500);
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS latitude DECIMAL(10,7);
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS longitude DECIMAL(10,7);
